### ISSUE TITLE
Documentation for running via docker-compose is incorrect

### ISSUE THREAD

**Issue by akinnee** [dmuth/splunk-network-health-check#5]
Based on the command generated by go.sh, the docker-compose file should look like this:

```
version: "3"

services:
  splunk-network-health-check:
    image: dmuth1/splunk-network-health-check
    restart: "unless-stopped"
    privileged: true
    volumes:
      - ./splunk-data:/data
      - ./user-prefs.conf:/opt/splunk/etc/users/admin/user-prefs/local/user-prefs.conf
    ports:
      - 8000:8000
    environment:
      TARGETS: "google.com,8.8.8.8,1.1.1.1"
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "password1"

```
